run_name: new_run
model_name: "facebook/vjepa2-vitl-fpc32-256-diving48"
predict_per_item: 16
model:
  fc_drop_rate: 0.5
  class_weights: inv_freq_sqrt
  freeze_encoder_layers: 14
data:
  chunk_length: 16
  chunk_shift: 16
  chunk_step: 1
  resize_to: 224
  do_aa: true
  part_sample: 1.0
training:
  epochs: 10
  train_bs: 1
  val_bs: 1
  num_workers: 0
  part_warmup: 0.2
  lr: 4.0e-5
  weight_decay: 0.1
  label_smoothing: 0.1
  compile: false
  patience: null
mixup_alpha: 0.8
ema_decay: 0.999
seed: 0
device: "mps"
starting_checkpoint: null
wandb:
  key: null
  entity: null
  project: feral_private
